erDiagram
    Usuario {int codigo String nome String email String username String password }
    Despesa {int codigo String nome Date dataCriacao int qtdProduto}
    Produto {String nome bollean tipo double peso int unidade double preco Date validade Date validadeAberto }
    Marca {int codigo String nome }
    Categoria {int codigo String nome }
    Estabelecimento {String nome Endereco endereco String modalidade String tipo }
    Compra {int codigo Date data String local }


    Usuario ||--|{Despesa: possui 
    Despesa ||--|{Produto: guarda
    Usuario ||--|{Compra: realiza
    Compra||--|{Produto: tem
    Compra }|--|{Estabelecimento: realizada
    Produto }|--||Marca: possui
    Produto }|--||Categoria: possui